<?php
/*------------------------------------------------------------------------
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

global $var_yttheme;  
// Include cpanel
if( $var_yttheme->getParam('showCpanel') ) { ?>
<div id="cpanel_wrapper" style="direction: ltr">
	<div class="cpanel-head">
		<span>Theme Settings</span>
		<div class="action cpanel-reset">
			<a class="btn btn-info reset" href="#" onclick="javascript: onCPResetDefault(TMPL_COOKIE);">Reset</a>
		</div>		
	</div>

	<div class="accordion" id="ytcpanel_accordion">
		<!--Theme-->
        <div class="accordion-group cpanel-theme-color">
            <div id="yt_cpanelaccordionfirst" class="accordion-heading">
                <a class="accordion-toggle"  data-parent="#ytcpanel_accordion" href="#ytitem_1">
					Theme Color
				</a>
            </div>
        	<div id="ytitem_1" class="accordion-theme">
                <div class="accordion-inner clearfix">
					<div class="color-theme">		
						<?php $currentUrl = Mage::getBaseUrl(); 
							$curentStore = Mage::app()->getStore()->getCode();
						?>			
						<a href="<?php echo $currentUrl."?___store=default&___from_store=".$curentStore?>">
						<span title="Default" class="theme-color default<?php echo ($var_yttheme->getParam('theme_color')=='default')?' active':'';?>">Default</span></a>
						<a href="<?php echo $currentUrl."?___store=german&___from_store=".$curentStore?>">
						<span title="Blue" class="theme-color blue<?php echo ($var_yttheme->getParam('theme_color')=='blue')?' active':'';?>">Blue</span>
						</a>
						<a href="<?php echo $currentUrl."?___store=spain&___from_store=".$curentStore?>">
						<span title="Green" class="theme-color green<?php echo ($var_yttheme->getParam('theme_color')=='green')?' active':'';?>">Green</span>
						</a>
						<a href="<?php echo $currentUrl."?___store=french&___from_store=".$curentStore?>">
						<span title="Red" class="theme-color red<?php echo ($var_yttheme->getParam('theme_color')=='red')?' active':'';?>">Red</span>
						</a>
						<a href="<?php echo $currentUrl."?___store=sweden&___from_store=".$curentStore?>">
						<span title="Pink" class="theme-color pink<?php echo ($var_yttheme->getParam('theme_color')=='pink')?' active':'';?>">Pink</span>
						</a>
						<a href="<?php echo $currentUrl."?___store=italy&___from_store=".$curentStore?>">
						<span title="Violet" class="theme-color violet<?php echo ($var_yttheme->getParam('theme_color')=='violet')?' active':'';?>">Violet</span>
						</a>

					</div>
				</div>
			</div>
        </div>
	
		<!--Store-->
		<div class="accordion-group cpanel-store">
			<div class="accordion-heading">
				<a class="accordion-toggle" data-parent="#ytcpanel_accordion" href="#ytitem_2">
				Layout Style</a>
			</div>
			<div id="ytitem_2" class="accordion-store">
				<div class="accordion-inner clearfix">
					<div class="cp-item">
						<div class="inner">
							<?php echo $this->getChildHtml('store_switcher');?>
						</div>
					</div>
					<!-- Select Layout -->
					<div class="cp-item layout-option">
						
						<div class="inner">
							<select onchange="javascript: onCPApply();" name="ytcpanel_layoutstyle" class="cp_select">
								<option value="1" <?php echo ($var_yttheme->getParam('layoutstyle')=='1')?' selected="selected"':'';?>>Full Width</option>
								<option value="2" <?php echo ($var_yttheme->getParam('layoutstyle')=='2')?' selected="selected"':'';?>>Boxed</option>
							</select>
						</div>
					</div>					
				</div>
			</div>
		</div>	
		<!-- Menu -->
		<div class="accordion-group cpanel-menu">
			<div class="accordion-heading">
				<a class="accordion-toggle" data-parent="#ytcpanel_accordion" href="#ytitem_6">
				Menu style </a>
			</div>
			<div id="ytitem_6" class="accordion-menu">
				<div class="accordion-inner clearfix">
					<!-- Styles -->
					<div class="cp-item footer-background-color">
						<!--span>Styles</span-->
						<div class="inner">
							<select onchange="javascript: onCPApply();" name="ytcpanel_menustyle" class="cp_select">
								<option value="mega" <?php echo ($var_yttheme->getParam('menustyle')=='mega')?' selected="selected"':'';?>>Mega</option>
								<option value="css" <?php echo ($var_yttheme->getParam('menustyle')=='css')?' selected="selected"':'';?>>Css</option>
							</select>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div id="cpanel_btn" class="normal">
		<i class="icon-hand-left"></i>
	</div>
</div>

<script type="text/javascript">
	// <![CDATA[
    jQuery(document).ready(function($){
      
		function templateSetting(array){
			if(array['0']){
				$('.body-background-color input.miniColors').attr('value', array['0']);
				$('.body-background-color a.miniColors-trigger').css('background-color', array['0']);
				$('input.ytcpanel_bgcolor').attr('value', array['0']);
			}
			if(array['1']){
				$('.link-color input.miniColors').attr('value', array['1']);
				$('.link-color a.miniColors-trigger').css('background-color', array['1']);
				$('input.ytcpanel_linkcolor').attr('value', array['1']);
			}
			if(array['2']){
				$('.text-color input.miniColors').attr('value', array['2']);
				$('.text-color a.miniColors-trigger').css('background-color', array['2']);
				$('input.ytcpanel_textcolor').attr('value', array['2']);
			}			
		}
		
		var array 			= Array('bgcolor','linkcolor','textcolor');
		var array_default	= Array('#FFFFFF','#444','#666');
		var array_blue 		= Array('#FFFFFF','#444','#666');
		var array_green   	= Array('#FFFFFF','#444','#666');
		var array_red   	= Array('#FFFFFF','#444','#666');
		var array_pink  	= Array('#FFFFFF','#444','#666');
		var array_violet   	= Array('#FFFFFF','#444','#666');
	

		$('.theme-color.default').click(function(){
			$($(this).parent().find('.active')).removeClass('active'); $(this).addClass('active');
			createCookie(TMPL_NAME+'_'+'theme_color', $(this).html().toLowerCase(), 365);
			templateSetting(array_default);
			onCPApply();
		});
		$('.theme-color.blue').click(function(){
			$($(this).parent().find('.active')).removeClass('active'); $(this).addClass('active');
			createCookie(TMPL_NAME+'_'+'theme_color', $(this).html().toLowerCase(), 365);
			templateSetting(array_blue);
			onCPApply();
		});
		$('.theme-color.green').click(function(){
			$($(this).parent().find('.active')).removeClass('active'); $(this).addClass('active');
			createCookie(TMPL_NAME+'_'+'theme_color', $(this).html().toLowerCase(), 365);
			templateSetting(array_green);
			onCPApply();
		});

		$('.theme-color.red').click(function(){
			$($(this).parent().find('.active')).removeClass('active'); $(this).addClass('active');
			createCookie(TMPL_NAME+'_'+'theme_color', $(this).html().toLowerCase(), 365);
			templateSetting(array_red);
			onCPApply();
		});
		$('.theme-color.pink').click(function(){
			$($(this).parent().find('.active')).removeClass('active'); $(this).addClass('active');
			createCookie(TMPL_NAME+'_'+'theme_color', $(this).html().toLowerCase(), 365);
			templateSetting(array_pink);
			onCPApply();
		});
		$('.theme-color.violet').click(function(){
			$($(this).parent().find('.active')).removeClass('active'); $(this).addClass('active');
			createCookie(TMPL_NAME+'_'+'theme_color', $(this).html().toLowerCase(), 365);
			templateSetting(array_violet);
			onCPApply();
		});
    });
	// ]]>
    </script>
<?php } ?>
