<?php 
global $var_yttheme;
?>
<div class="socials-wrap">
	<ul>
		<?php if( $var_yttheme->getParam('show_facebook') == 1 ){ ?>
			<li><a class="f" title="<?php echo $var_yttheme->getParam('facebook_name');?>" href="<?php echo $var_yttheme->getParam('facebook_url');?>" target="_blank" data-icon="f"><?php echo $var_yttheme->getParam('facebook_name');?></a></li>
		<?php }?>
		<?php if( $var_yttheme->getParam('show_twitter') == 1 ){ ?>
			<li><a class="t" title="<?php echo $var_yttheme->getParam('twitter_name');?>" href="<?php echo $var_yttheme->getParam('twitter_url');?>" target="_blank" data-icon="l"><?php echo $var_yttheme->getParam('twitter_name');?></a></li>
		<?php }?>		
		<?php if( $var_yttheme->getParam('show_pinterest') == 1 ){ ?>
			<li><a class="p" title="<?php echo $var_yttheme->getParam('pinterest_name');?>" href="<?php echo $var_yttheme->getParam('pinterest_url');?>" target="_blank" data-icon="&"><?php echo $var_yttheme->getParam('pinterest_name');?></a></li>
		<?php }?>			
		<?php if( $var_yttheme->getParam('show_google') == 1 ){ ?>
			<li><a class="g" title="<?php echo $var_yttheme->getParam('google_name');?>" href="<?php echo $var_yttheme->getParam('google_url');?>" target="_blank" data-icon="g"><?php echo $var_yttheme->getParam('google_name');?></a></li>
		<?php }?>
		<?php if( $var_yttheme->getParam('show_rss') == 1 ){ ?>
			<li><a class="r" title="<?php echo $var_yttheme->getParam('rss_name');?>" href="<?php echo $var_yttheme->getParam('rss_url');?>" target="_blank" data-icon="i"><?php echo $var_yttheme->getParam('rss_name');?></a></li>
		<?php }?>	
	</ul>
</div>    
			
