<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.2.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?> 
<?php $posts = $this->getPosts(); ?>
<div class="wrap-blog-list"> 
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?> 
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?> 
</div>

 <div class="blog-title">
 	<h2><?php echo $this->__('OUR BLOG'); ?></h2>
 </div>
<ol id="blog-list" class="products-list">	
<?php
 foreach ($posts as $post): ?>
    <li class="postWrapper item">
		<div class="item-inner">
			<div class="product-info">
				<div class="product-name">
					<h2><a class="title-blog-name" href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
				</div>
				<div class="info-cat-blog">
					<?php 
					//date_default_timezone_set("America/Los_Angeles");
					//print_r(date("Y-m-d H:i:s",strtotime($post->getCreatedTime())));
					//echo "<br>";
					//print_r(date("l, F j, Y H:i:s A",strtotime($post->getCreatedTime())));
					echo $post->getCreatedTime();?>
				</div>					
					<div class="postContent">
						<?php echo $post->getPostContent(); ?>
						<div class="bottom-info-blog">
							<ul class="list-info-bottom">
								<li>
									<?php if ($this->getCommentsEnabled()): ?>									
										<a class="link-comment" href="<?php echo $post->getAddress(); ?>#commentBox" ><?php echo $post->getCommentCount(); ?> <?php if($post->getCommentCount()<=1) echo $this->__('Comment'); ?>  <?php if($post->getCommentCount()>1) echo $this->__('Comments'); ?></a>
									<?php endif; ?>
								</li>
								<li>&nbsp;|&nbsp;</li>
								<li>
									<?php echo $this->__("Posted By:"); ?> <span class="user-wr"><?php echo $post->getUser(); ?></span>
								</li>
							</ul>
						</div>
						
					</div>
					
			</div>
		</div>
    </li>
<?php endforeach; ?>
</ol> 
<div class="toolbar-bottom toolbar-cat">
 <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
 </div>
 <script type="text/javascript">                
        jQuery(document).ready(function($){
           $('.selected-limiter').click(function(){
            $('.select-limiter').toggleClass('current-item');
            });
            $('.selected-order').click(function(){
                $('.select-order').toggleClass('current-item');
            });
        });
    </script>

</div>